### ISSUE TITLE
Tenant apps showing up in admin for public schema

### ISSUE THREAD

**Issue by brechmos** [owais/django-tenant-schemas#1]
Hey, thanks for working on this.  I appear to be having a problem and I am not sure if it is a bug or if is an understanding error (ie me). 

I am testing my site so created a short script to reset my site:
    #! /bin/zsh

```
psql -U postgres -W -c 'drop database <database>; '
psql -U postgres -W -c 'create database <database>'
source env/bin/activate
python manage.py migrate_schemas --shared

echo """
  from customers.models import Client
  c = Client(name='Public', paid_until='2014-01-10', domain_url='public.com',schema_name='public')
  c.save()
""" | python manage.py shell

echo """
  from customers.models import Client
  c = Client(name='Public', paid_until='2014-01-10', domain_url='a.example.com',schema_name='schemaA')
  c.save()
""" | python manage.py shell
```

My settings file contains:

```
SHARED_APPS = (

    'customers', # you must list the app where your tenant model resides in

    'django.contrib.contenttypes',

    # everything below here is optional
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',

    'tenant_schemas',  # mandatory
)

TENANT_APPS = (
     'django.contrib.contenttypes',
     'django.contrib.auth',

      'hotels',
      'link',  # my model
)

INSTALLED_APPS =  list(OrderedDict.fromkeys(( ('tenant_schemas',) + TENANT_APPS + SHARED_APPS  ) ) )
```

So, when I do this, I see Hotels and Links in my Admin site for the public schema (public URL).  As I understand, I shouldn't. I _do_ have hotels/admin.py: 

```
from django.contrib import admin
from .models import Hotels
admin.site.register( Hotels )
```

When I try clicking on Hotels in the Admin panel it comes up with query error saying the hotels table does not exist. 

What is not clear to me is if this is a bug (less likely) or a understanding/process issue (more likely).  Surely I can still use the admin section (?).  Should the "Hotels" still show up in the admin section for the public url/schema?  I tried following what you and bernardopires documented but I am not sure if the process changed given 1.7 and migrate.  I am using Python 2.7 and Django 1.7.

Any help would be greatly appreciated.  I am happy to test anything you want.

**Comment by brechmos** [comment]
The more I think about this, the more I think it is I probably should post this under bernardopires rather than here as it is likely independent of the 1.7 upgrade.  If you don't mind I'll leave the question here as I don't have Django < 1.7 setup to test this all on...

**Comment by owais** [comment]
@brechmos Would it be possible for you to test this under 1.6 and report back? I would really appreciate if you could confirm if the behaviour is specific to 1.7.

**Comment by brechmos** [comment]
Yeah, it actually does appear to be as such in bernardopires so it is not an issue with your work. I'll bring ask over there.
